# Testing all models with balanced (at 60)

## Imports required:

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_squared_error,r2_score,accuracy_score, confusion_matrix,f1_score
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.svm import SVR,SVC
from sklearn.neighbors import KNeighborsClassifier ,KNeighborsRegressor
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor, StackingClassifier
from xgboost import XGBClassifier


## Regression models:

### Data split

In [2]:
df= pd.read_csv("balanced60.csv")

X = df.drop(columns=['popularity'])  # Replace 'target_column' with your actual target variable
y = df['popularity']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
y_train = y_train.squeeze()
y_test = y_test.squeeze()


### Linear regression:

In [3]:
# Initialize the model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate Mean Squared Error & R-squared Score
mse = mean_squared_error(y_test, y_pred)
r2 = model.score(X_test, y_test)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared Score: {r2:.4f}")

# Tolerance-Based Accuracy Calculation
tolerance = 10  # Absolute error margin

# Count correct predictions within tolerance
correct_predictions = np.sum(np.abs(y_test - y_pred) <= tolerance)

# Calculate accuracy
accuracy_with_tolerance = (correct_predictions / len(y_test)) * 100

print(f"Model Accuracy (with ±{tolerance}% tolerance): {accuracy_with_tolerance:.2f}%")


Mean Squared Error: 416.5355
R-squared Score: 0.0259
Model Accuracy (with ±10% tolerance): 35.46%


### Polynomial Regression:

In [4]:
# Set polynomial degree
degree = 3  # You can experiment with higher degrees

# Transform features into polynomial features
poly = PolynomialFeatures(degree=degree)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# Initialize and train the model
model = LinearRegression()
model.fit(X_train_poly, y_train)

# Make predictions
y_pred = model.predict(X_test_poly)

# Calculate Mean Squared Error & R-squared Score
mse = mean_squared_error(y_test, y_pred)
r2 = model.score(X_test_poly, y_test)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared Score: {r2:.4f}")

# Tolerance-Based Accuracy Calculation
tolerance = 10  # Absolute error margin
correct_predictions = np.sum(np.abs(y_test - y_pred) <= tolerance)
accuracy_with_tolerance = (correct_predictions / len(y_test)) * 100

print(f"Model Accuracy (with ±{tolerance}% tolerance): {accuracy_with_tolerance:.2f}%")

Mean Squared Error: 409.7253
R-squared Score: 0.0419
Model Accuracy (with ±10% tolerance): 36.54%


### KNN Regressor:

In [5]:
# Initialize the model (choose k=5 as a starting point)
model = KNeighborsRegressor(n_neighbors=5)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate Mean Squared Error & R-squared Score
mse = mean_squared_error(y_test, y_pred)
r2 = model.score(X_test, y_test)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared Score: {r2:.4f}")

# Tolerance-Based Accuracy Calculation (±10 margin)
tolerance = 10  # Absolute error margin

# Count correct predictions within tolerance
correct_predictions = np.sum(np.abs(y_test - y_pred) <= tolerance)

# Calculate tolerance-based accuracy
accuracy_with_tolerance = (correct_predictions / len(y_test)) * 100
print(f"Model Accuracy (with ±{tolerance} margin): {accuracy_with_tolerance:.2f}%")


Mean Squared Error: 494.6176
R-squared Score: -0.1567
Model Accuracy (with ±10 margin): 37.00%


### Random Forest Regression:

In [6]:
# Initialize the model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Calculate Mean Squared Error & R-squared Score
mse = mean_squared_error(y_test, y_pred)
r2 = model.score(X_test, y_test)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared Score: {r2:.4f}")

# Tolerance-Based Accuracy Calculation (±10 margin)
tolerance = 10  # Absolute error margin

# Count correct predictions within tolerance
correct_predictions = np.sum(np.abs(y_test - y_pred) <= tolerance)

# Calculate tolerance-based accuracy
accuracy_with_tolerance = (correct_predictions / len(y_test)) * 100
print(f"Model Accuracy (with ±{tolerance} margin): {accuracy_with_tolerance:.2f}%")


Mean Squared Error: 424.3915
R-squared Score: 0.0076
Model Accuracy (with ±10 margin): 36.79%


### SVR

In [7]:
# Standardize features and target
scaler_X = StandardScaler()
scaler_y = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

# Reshape y to 2D before scaling, then back to 1D
y_train_scaled = scaler_y.fit_transform(y_train.values.reshape(-1, 1)).ravel()
y_test_scaled = scaler_y.transform(y_test.values.reshape(-1, 1)).ravel()

# Initialize the model with RBF kernel (default)
model = SVR(kernel='rbf')

# Train the model
model.fit(X_train_scaled, y_train_scaled)
y_pred_scaled = model.predict(X_test_scaled)

# Convert predictions back to original scale
y_pred = scaler_y.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()

# Calculate Mean Squared Error & R-squared Score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse:.4f}")
print(f"R-squared Score: {r2:.4f}")

# Tolerance-Based Accuracy Calculation (±10 margin)
tolerance = 10  # Absolute error margin

# Count correct predictions within tolerance
correct_predictions = np.sum(np.abs(y_test - y_pred) <= tolerance)

# Calculate tolerance-based accuracy
accuracy_with_tolerance = (correct_predictions / len(y_test)) * 100
print(f"Model Accuracy (with ±{tolerance} margin): {accuracy_with_tolerance:.2f}%")


Mean Squared Error: 426.9038
R-squared Score: 0.0017
Model Accuracy (with ±10 margin): 42.82%


## Classification models:

### Logistical Regression

In [6]:
# Load dataset
df = pd.read_csv("balanced60.csv")

threshold = 60  # Set threshold to 70

# Create a fresh copy of the data
data = df.copy()

# Convert popularity to binary based on the threshold
data['popularity'] = (data['popularity'] > threshold).astype(int)

# Define features and target
X = data.drop(columns=['popularity'])
y = data['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Logistic Regression model
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"Threshold: {threshold}")
print(f"Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Threshold: 60
Model Accuracy: 56.82%
F1 Score: 0.5276690888764674
Confusion Matrix:
[[640 389]
 [456 472]]


### KNN 

In [7]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 60
print("=" * 50)
print(f"Testing Threshold: {threshold}")

# Binarize target based on threshold
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# KNN model
k = 25
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train_scaled, y_train)

# Predict
y_pred = knn.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"KNN Model with k={k}")
print(f"Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Testing Threshold: 60
KNN Model with k=25
Model Accuracy: 58.87%
F1 Score: 0.5783132530120482
Confusion Matrix:
[[600 429]
 [376 552]]


### RFC

In [8]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 60
print("=" * 50)
print(f"Testing Threshold: {threshold}")

# Convert target variable: Popularity > threshold → 1, else 0
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Split data (80% train, 20% test) with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Feature scaling (optional for Random Forest, but kept for consistency)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train Random Forest model
rfc = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    class_weight="balanced",
    max_depth=20,
    min_samples_split=5
)
rfc.fit(X_train_scaled, y_train)

# Make predictions
y_pred = rfc.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
# Confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Testing Threshold: 60
Model Accuracy: 59.27%
F1 Score: 0.5721953837895867
Confusion Matrix:
 [[627 402]
 [395 533]]


### SVM

In [9]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 60
print("=" * 50)
print(f"Testing Threshold: {threshold}")

# Convert popularity to binary target
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize and train SVM
svm = SVC(kernel='rbf', C=1, probability=True, random_state=42)
svm.fit(X_train_scaled, y_train)

# Predictions
y_pred = svm.predict(X_test_scaled)

# Evaluation
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"SVM Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Testing Threshold: 60
SVM Model Accuracy: 58.97%
F1 Score: 0.5930055752660922
Confusion Matrix:
 [[569 460]
 [343 585]]


### XGB 

In [10]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 60
print("=" * 50)
print(f"Testing Threshold: {threshold}")

# Convert popularity to binary based on threshold
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Initialize XGBoost Classifier
xgb = XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=8,
    random_state=42,
    scale_pos_weight=5
)

# Train model
xgb.fit(X_train_scaled, y_train)

# Predict
y_pred = xgb.predict(X_test_scaled)

# Evaluation
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"XGBoost Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
print("Confusion Matrix:\n")
cm = confusion_matrix(y_test, y_pred)
print(cm)

Testing Threshold: 60
XGBoost Model Accuracy: 56.00%
F1 Score: 0.6664083688492832
Confusion Matrix:

[[236 793]
 [ 68 860]]


### stacking models


In [11]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 60
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define base models
base_models = [
    ('svm', SVC(kernel='rbf', C=1, probability=True, random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('rfc', RandomForestClassifier(n_estimators=100, random_state=42))
]

# Define meta-model (stacker)
meta_model = LogisticRegression()

# Create StackingClassifier
stacked_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

# Train stacked model
stacked_model.fit(X_train_scaled, y_train)

# Predict
y_pred = stacked_model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"Stacked Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Stacked Model Accuracy: 59.53%
F1 Score: 0.5540540540540541
Confusion Matrix:
[[673 356]
 [436 492]]


In [12]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 70
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define base models
base_models = [
    ('svm', SVC(kernel='rbf', C=1, probability=True, random_state=42)),
    ('knn', KNeighborsClassifier(n_neighbors=5)),

]

# Define meta-model (stacker)
meta_model = LogisticRegression()

# Create StackingClassifier
stacked_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

# Train stacked model
stacked_model.fit(X_train_scaled, y_train)

# Predict
y_pred = stacked_model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"Stacked Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Stacked Model Accuracy: 80.58%
F1 Score: 0.010416666666666666
Confusion Matrix:
[[1575    1]
 [ 379    2]]


In [13]:
# Load dataset
df = pd.read_csv("balanced60.csv")

# Set threshold
threshold = 70
df['popularity'] = (df['popularity'] > threshold).astype(int)

# Define features and target
X = df.drop(columns=['popularity'])
y = df['popularity']

# Train-test split with stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define base models
base_models = [
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('rfc', RandomForestClassifier(n_estimators=100, random_state=42))
]

# Define meta-model (stacker)
meta_model = LogisticRegression()

# Create StackingClassifier
stacked_model = StackingClassifier(
    estimators=base_models,
    final_estimator=meta_model,
    cv=5
)

# Train stacked model
stacked_model.fit(X_train_scaled, y_train)

# Predict
y_pred = stacked_model.predict(X_test_scaled)

# Evaluate
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"Stacked Model Accuracy: {accuracy:.2f}%")
f1 = f1_score(y_test, y_pred)

print("F1 Score:", f1)
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Stacked Model Accuracy: 80.48%
F1 Score: 0.030456852791878174
Confusion Matrix:
[[1569    7]
 [ 375    6]]
